<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx8OVGA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx8OVGA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCx8OVGA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCx8OVGA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCx8OVGA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cx8OVGA',
    'container.build_id' => '97f865da',
    'container.build_time' => 1638461876,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx8OVGA');
