<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK2jmNWv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK2jmNWv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK2jmNWv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK2jmNWv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK2jmNWv\App_KernelDevDebugContainer([
    'container.build_hash' => 'K2jmNWv',
    'container.build_id' => '43cac172',
    'container.build_time' => 1638463830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK2jmNWv');
