<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'employe' => [[], ['_controller' => 'App\\Controller\\EmployeController::index'], [], [['text', '/employe']], [], []],
    'app_employeAjout' => [[], ['_controller' => 'App\\Controller\\EmployeController::AjoutEmploye'], [], [['text', '/employeAjout/']], [], []],
    'app_employeAjoutHash' => [[], ['_controller' => 'App\\Controller\\EmployeController::registration'], [], [['text', '/employeAjoutHash/']], [], []],
    'app_employeAuth' => [[], ['_controller' => 'App\\Controller\\EmployeController::authEmploye'], [], [['text', '/employeAuth/']], [], []],
    'app_formationAff' => [[], ['_controller' => 'App\\Controller\\EmployeController::formationAff'], [], [['text', '/formationAff/']], [], []],
    'app_inscriptionEmployeFormation' => [['id'], ['_controller' => 'App\\Controller\\EmployeController::inscriptionEmployeFormation'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/inscriptionEmployeFormation']], [], []],
    'formation' => [[], ['_controller' => 'App\\Controller\\FormationController::index'], [], [['text', '/formation']], [], []],
    'app_formationAjout' => [[], ['_controller' => 'App\\Controller\\FormationController::AjoutFormation'], [], [['text', '/formationAjout/']], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\InscriptionController::index'], [], [['text', '/inscription']], [], []],
    'app_inscriptionAjout' => [[], ['_controller' => 'App\\Controller\\InscriptionController::AjoutInscription'], [], [['text', '/inscriptionAjout/']], [], []],
    'produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::index'], [], [['text', '/produit']], [], []],
    'app_produitAjout' => [[], ['_controller' => 'App\\Controller\\ProduitController::AjoutProduit'], [], [['text', '/produitAjout/']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
